// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2g2esyUfQlcL7Q1UGJajpFjpz9OOX03g',
    appId: '1:225752926575:web:326eb53809acc54dda809a',
    messagingSenderId: '225752926575',
    projectId: 'casagarcia-34d18',
    authDomain: 'casagarcia-34d18.firebaseapp.com',
    storageBucket: 'casagarcia-34d18.firebasestorage.app',
    measurementId: 'G-NQXVD6YPFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNz3KI_6npFyouwl_OnI9rPqvSezmcRkE',
    appId: '1:225752926575:android:691cfbb696443deada809a',
    messagingSenderId: '225752926575',
    projectId: 'casagarcia-34d18',
    storageBucket: 'casagarcia-34d18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDpXfwTCLwfq-cL5djAdk_JWbv8-bek4U',
    appId: '1:225752926575:ios:6ff0515bd07d56f3da809a',
    messagingSenderId: '225752926575',
    projectId: 'casagarcia-34d18',
    storageBucket: 'casagarcia-34d18.firebasestorage.app',
    iosBundleId: 'com.example.casaGarcia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDpXfwTCLwfq-cL5djAdk_JWbv8-bek4U',
    appId: '1:225752926575:ios:6ff0515bd07d56f3da809a',
    messagingSenderId: '225752926575',
    projectId: 'casagarcia-34d18',
    storageBucket: 'casagarcia-34d18.firebasestorage.app',
    iosBundleId: 'com.example.casaGarcia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2g2esyUfQlcL7Q1UGJajpFjpz9OOX03g',
    appId: '1:225752926575:web:3737a2ce537d3579da809a',
    messagingSenderId: '225752926575',
    projectId: 'casagarcia-34d18',
    authDomain: 'casagarcia-34d18.firebaseapp.com',
    storageBucket: 'casagarcia-34d18.firebasestorage.app',
    measurementId: 'G-PKP9NF4PSE',
  );
}
